#!/usr/bin/env python3
"""The editor API index must list every class the libraries define.

Usage:
  check_api_index.py                             # check the committed copies
  check_api_index.py --regenerated <path>        # also compare against a fresh run
  check_api_index.py --committed <saved> --packaged <saved> --regenerated <path>

The third form is what CI uses: gen_json.sh overwrites both tracked copies in
place, so the committed ones are saved first and named explicitly. Pointing
--regenerated at the tracked path without that would compare the fresh index
against itself and pass unconditionally.

`tools/lsp/server/objk_apis.json` is what the language server answers
completions and hover from, and `tools/lsp/clients/vscode/server/objk_apis.json`
is the copy packaged into the `.vsix` -- the one users actually get. Both are
tracked, both are generated by `tools/lsp/server/doc_json/gen_json.{cmd,sh}`,
and until this file existed **nothing regenerated or verified either of them**:

    $ grep -rn 'objk_apis\\|gen_json' .github/workflows/*.yml
    (no matches)

So the index changed only when someone remembered. They had not remembered.
Regenerating on 2026-10-07 took `API.Onnx` from 48 entries to 58: the whole
generic run API (#1047) had shipped with no editor support, and several
System.ML releases before it had too -- FoldSplit, GroupRecall, AucMetric,
RecallAtFprMetric, AveragePrecisionMetric and the three tree classifiers
(#1050).

## Why this is not the same as check_doc_lists.py

That one guards the six hard-coded lists of `lib_src/*.obs`, and it works: it
caught `inference` missing from all six, including the sixth that had been
forgotten. But a library being in every list says nothing about whether the
index was regenerated afterwards. A library can be listed everywhere and still
absent from the index, which is exactly the state this tree was in.

## Why it compares the CLASS SET and not the bytes

A byte diff would be stricter and would also fail for reasons nobody can act
on. The index is generated by an Objeck program whose output ordering comes from
the iteration order of its collections; the committed copy is produced on
whatever machine the maintainer used, and this check runs on ubuntu. Formatting
and ordering are not what drifts -- missing classes are -- and a guard that
reddens CI over whitespace gets disabled.

So: with --regenerated, the comparison is over the keys of `class-details`,
which are fully-qualified class names.

## The positive control

CONTROL names classes that must be present. A scan that reads a truncated,
empty or wrong file would otherwise report a clean index, and a clean result
from a check that cannot see a known positive is indistinguishable from a clean
tree -- the lesson check_native_write_barrier.py was written around. Three of
these four were absent from the committed index as recently as 2026-10-07, so
they are not hypothetical.

## Limits, stated rather than papered over

- It compares `class-details`, keyed by fully-qualified name. It does NOT check
  `class-bundle-names`, which is keyed by SHORT name and therefore cannot hold
  two classes that share one: `Tensor` resolves to `API.Onnx` and not
  `API.Inference`, `Client` to `Data.JSON.RPC`, `EndPoint` to `API.OpenAI`.
  That shadowing is a separate defect in the index's shape, not drift, and
  tightening this check would not fix it.
- Without --regenerated it verifies only that the two copies agree with each
  other and that the control classes are present. That catches a desynced
  `.vsix` copy but not a stale pair; the CI step passes --regenerated.
- It says nothing about whether a class's *contents* are current -- a method
  added to an already-indexed class is not caught. The class set is the part
  that went wrong.
"""

import argparse
import io
import json
import os
import sys

SERVER = os.path.join("tools", "lsp", "server", "objk_apis.json")
VSCODE = os.path.join("tools", "lsp", "clients", "vscode", "server", "objk_apis.json")

# Must be present. See "The positive control" above; the first three were all
# genuinely missing from the committed index on 2026-10-07.
CONTROL = [
    "API.Onnx.Session",         # the generic run entry point (#1047)
    "API.Onnx.RunResult",       # ditto
    "System.ML.FoldSplit",      # the 2026-10 System.ML phases
    "Collection.Vector",        # present since long before any of this
]


def fail(message):
    print("FAIL: %s" % message, file=sys.stderr)
    sys.exit(1)


def load(path):
    if not os.path.isfile(path):
        fail("%s does not exist" % path)
    try:
        with io.open(path, encoding="utf-8") as handle:
            return json.load(handle)
    except ValueError as err:
        fail("%s is not valid JSON: %s" % (path, err))


def class_names(index, path):
    details = index.get("class-details")
    if not isinstance(details, dict):
        fail("%s has no 'class-details' object" % path)
    if not details:
        fail("%s has an empty 'class-details'" % path)
    return set(details.keys())


def libraries_by_bundle(index):
    """bundle name -> .obl, for a message that can be acted on.

    Keyed by BUNDLE and deliberately not by short class name. `class-bundle-names`
    is keyed by short name and therefore cannot hold two classes that share one:
    looking up `Client` there returns Data.JSON.RPC, `Tensor` returns API.Onnx and
    `EndPoint` returns API.OpenAI. Doing this the obvious way made this check
    report three of four API.Inference classes against the wrong library, which is
    worse than reporting none -- someone would have gone and looked at json_rpc.
    """
    out = {}
    for entry in index.get("class-bundle-names", {}).values():
        if isinstance(entry, dict) and entry.get("bundle") and entry.get("file"):
            out.setdefault(entry["bundle"], entry["file"])
    return out


def library_of(libraries, fqn):
    """Which .obl a fully-qualified class comes from.

    A class name holds no dots, so everything before the last one is the bundle.
    """
    if "." not in fqn:
        return "unknown library"
    return libraries.get(fqn.rsplit(".", 1)[0], "unknown library")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--regenerated", metavar="PATH",
                        help="a freshly generated index to compare the class set against")
    parser.add_argument("--root", default=".", help="repository root")
    # gen_json.sh overwrites both tracked copies IN PLACE, so a caller that
    # regenerates before running this has to say where it kept the committed
    # ones. Without that it would be comparing the fresh index against itself
    # and passing unconditionally.
    parser.add_argument("--committed", metavar="PATH",
                        help="the committed server index (default: <root>/%s)" % SERVER)
    parser.add_argument("--packaged", metavar="PATH",
                        help="the committed .vsix index (default: <root>/%s)" % VSCODE)
    args = parser.parse_args()

    server_path = args.committed or os.path.join(args.root, SERVER)
    vscode_path = args.packaged or os.path.join(args.root, VSCODE)

    # 1. the packaged copy must match the server's. This one silently shipped
    #    older than the server's for as long as gen_json wrote only one of them.
    server_bytes = open(server_path, "rb").read() if os.path.isfile(server_path) else None
    vscode_bytes = open(vscode_path, "rb").read() if os.path.isfile(vscode_path) else None
    if server_bytes is None:
        fail("%s does not exist" % server_path)
    if vscode_bytes is None:
        fail("%s does not exist" % vscode_path)
    if server_bytes != vscode_bytes:
        fail("the two index copies differ.\n"
             "  %s  %d bytes\n"
             "  %s  %d bytes\n"
             "The second is packaged into the .vsix, so it is the index users get.\n"
             "Regenerate with tools/lsp/server/doc_json/gen_json.sh, which writes both."
             % (server_path, len(server_bytes), vscode_path, len(vscode_bytes)))

    committed = load(server_path)
    have = class_names(committed, server_path)

    # 2. the positive control
    missing_control = [name for name in CONTROL if name not in have]
    if missing_control:
        fail("the index is missing classes that must be there: %s\n"
             "Either it is badly out of date, or this check is reading the wrong file.\n"
             "Both are reasons to stop rather than report a clean index."
             % ", ".join(missing_control))

    print("both index copies agree: %d classes, control %d/%d"
          % (len(have), len(CONTROL) - len(missing_control), len(CONTROL)))

    if not args.regenerated:
        print("PASS: no --regenerated given, so staleness was not checked")
        return

    fresh_path = args.regenerated
    fresh = load(fresh_path)
    want = class_names(fresh, fresh_path)

    absent = sorted(want - have)
    extra = sorted(have - want)

    if absent or extra:
        lines = ["the committed index does not match a fresh generation."]
        if absent:
            libraries = libraries_by_bundle(fresh)
            lines.append("")
            lines.append("  %d class(es) the libraries define but the index omits:" % len(absent))
            for name in absent[:40]:
                lines.append("    %-52s %s" % (name, library_of(libraries, name)))
            if len(absent) > 40:
                lines.append("    ... and %d more" % (len(absent) - 40))
        if extra:
            lines.append("")
            lines.append("  %d class(es) in the index that no longer exist:" % len(extra))
            for name in extra[:40]:
                lines.append("    %s" % name)
            if len(extra) > 40:
                lines.append("    ... and %d more" % (len(extra) - 40))
        lines.append("")
        lines.append("Regenerate and commit both copies:")
        lines.append("  sh tools/lsp/server/doc_json/gen_json.sh    (or gen_json.cmd on Windows)")
        fail("\n".join(lines))

    print("PASS: the committed index matches a fresh generation (%d classes)" % len(have))


if __name__ == "__main__":
    main()
