GTK_INCS=`pkg-config --cflags gtk+-2.0`
GTK_LIBS=`pkg-config --cflags --libs gtk+-2.0`
# ARGS=-O3 -shared -fPIC $(GTK_INCS) -Wno-deprecated -D_X64 -pthread -D_X64
ARGS=-g -D_DEBUG -shared -fPIC $(GTK_INCS) -Wno-deprecated -D_X64 -pthread -D_X64

CC=g++
SRC=gtk2_objk.o
EXE=ojk_gtk.1.dylib 

$(EXE): $(SRC)
	$(CC) -m64 -pthread -dynamiclib $(GTK_LIBS) -o $(EXE) $(SRC)

%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	rm -f $(EXE).exe $(EXE) *.dylib *.o *~
