GTK_INCS=`pkg-config --cflags gtk+-2.0`
GTK_LIBS=`pkg-config --cflags --libs gtk+-2.0`
ARGS=-g -D_DEBUG -D_MINGW  -Wall $(GTK_INCS)

CC=g++
SRC=gtk2_objk.o
EXE=ojk_gtk.so

# g++  -g -c -Wno-deprecated -Wall -D_MINGW $1.cpp
# g++ -shared -Wl,-soname,$1.so.1 -o $1.so $1.o

$(EXE): $(SRC)
	$(CC) -m32 -shared -D_MINGW -Wl,-soname,gtk2_objk.so.1 -o $(EXE) $(SRC) $(GTK_LIBS)

%.o: %.cpp
	$(CC) -m32 -D_MINGW $(ARGS) -c $< 

clean:
	rm -f $(EXE).exe $(EXE) *.dylib *.o *~
