GTK_INCS=`pkg-config --cflags gtk+-3.0`
GTK_LIBS=`pkg-config --cflags --libs gtk+-3.0`
# ARGS=-O3 -shared -fPIC $(GTK_INCS) -Wno-deprecated -D_X64 -pthread -D_X64
ARGS=-g -D_DEBUG -fPIC $(GTK_INCS) -Wno-deprecated -D_X64 -pthread -D_X64

CC=g++
SRC=gtk2_objk.o
EXE=ojk_gtk.1.so 

$(EXE): $(SRC)
	$(CC) -m64 -shared -pthread $(GTK_LIBS) -o $(EXE) $(SRC)

%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	rm -f $(EXE).exe $(EXE) *.o *~
