# ARGS=-g -D_SANITIZE -pthread -Wall -Wno-unused-function
ARGS=-O3 -pthread -Wall -Wno-unused-function
# ARGS=-pg -O3 -pthread -Wall -Wno-unused-function
# ARGS=-g -D_DEBUG -Wall -pthread -Wall -Wno-unused-function

CC=g++
SRC=common.o interpreter.o loader.o vm.o posix_main.o 
OBJ_LIBS= jit_intel_lp32.a memory.a
MEM_PATH=os/posix
JIT_PATH=jit/ia32
EXE=obr

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m32 -o $(EXE) $(SRC) $(OBJ_LIBS) -lssl -lcrypto -ldl -pthread
#	$(CC) -m32 -o $(EXE) $(SRC) $(OBJ_LIBS) -lssl -lcrypto -ldl -pthread -pg



memory.a:
	cd $(MEM_PATH); make	
	
jit_intel_lp32.a:
	cd $(JIT_PATH); make	
	
%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	cd $(MEM_PATH); make clean
	cd $(JIT_PATH); make clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~

