##############
# For Posix
##############
ARGS=-O3 -pthread -D_JIT_SERIAL -Wall
# ARGS=-g -D_DEBUG -D_JIT_SERIAL -Wunused -pthread -Wall

CC=g++
SRC=common.o interpreter.o loader.o vm.o posix_main.o 
OBJ_LIBS= jit_intel_lp32.a memory.a
MEM_PATH=os/posix
JIT_PATH=jit/ia32
EXE= obr

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m32 -o $(EXE) $(SRC) $(OBJ_LIBS) -ldl -pthread

memory.a:
	cd $(MEM_PATH); make	
	
jit_intel_lp32.a:
	cd $(JIT_PATH); make	
	
%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	cd $(MEM_PATH); make clean
	cd $(JIT_PATH); make clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~

