##############
# For Posix
##############
# ARGS=-g -D_DEBUG -D_JIT_SERIAL -Wall -D_X64 -pthread
ARGS=-O3 -pthread -D_X64 -D_JIT_SERIAL -Wall

CC=g++
SRC=common.o interpreter.o loader.o vm.o posix_main.o 
OBJ_LIBS= jit_amd_lp64.a memory.a
MEM_PATH= os/posix
JIT_PATH= jit/amd64
EXE= obr

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m64 -o $(EXE) $(SRC) $(OBJ_LIBS) -pthread -ldl

memory.a:
	cd $(MEM_PATH); make	
	
jit_amd_lp64.a:
	cd $(JIT_PATH); make	
	
%.o: %.cpp
	$(CC) -m64 $(A GS) -c $< 
six
##############


clean:
	cd $(MEM_PATH); make clean
	cd $(JIT_PATH); make clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
