# ARGS=-g -Wunused -D_X64 -pthread
# ARGS=-g -D_DEBUG -D_SERIAL -Wunused -D_X64 -pthread
# ARGS=-g -D_DEBUG -Wunused -pthread -D_X64
# ARGS=-g -D_DEBUG -Wunused -D_JIT_SERIAL -pthread -D_X64
ARGS=-O3 -D_JIT_SERIAL -pthread -D_X64

CC=g++
SRC=common.o interpreter.o loader.o vm.o posix_main.o 
OBJ_LIBS= jit_amd_lp64.a memory.a
MEM_PATH= os/posix
JIT_PATH= jit/amd64
EXE= obr

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m64 -pthread -o $(EXE) $(SRC) $(OBJ_LIBS)

memory.a:
	cd $(MEM_PATH); make	
	
jit_amd_lp64.a:
	cd $(JIT_PATH); make	
	
%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	cd $(MEM_PATH); make clean
	cd $(JIT_PATH); make clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
