##############
# For OSX only
##############
# ARGS=-pthread -mstackrealign -O3
# ARGS=-pthread -D_TIMING -mstackrealign -O3
ARGS=-pthread -mstackrealign -g -D_DEBUG -Wunused
# ARGS=-g -mstackrealign -Wunused -D_DEBUG -pthread -D_DEBUGGER

##############
# For Linux
##############
# ARGS=-g -Wunused -pthread
# ARGS=-g -D_DEBUG -D_SERIAL -Wunused -pthread
# ARGS=-g -D_DEBUG -Wunused -pthread
# ARGS=-g -Wunused -D_JIT_SERIAL -pthread
# ARGS=-O3 -pthread

CC=g++
SRC=common.o interpreter.o loader.o vm.o posix_main.o 
OBJ_LIBS= jit_intel_lp32.a memory.a debugger.a
MEM_PATH=os/posix
JIT_PATH=jit/ia32
DEBUG_PATH=debugger
EXE= obr

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m32 -pthread -o $(EXE) $(SRC) $(OBJ_LIBS)

memory.a:
	cd $(MEM_PATH); make	
	
jit_intel_lp32.a:
	cd $(JIT_PATH); make	
	
debugger.a:
	cd $(DEBUG_PATH); make	
	
%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	cd $(MEM_PATH); make clean
	cd $(JIT_PATH); make clean
	cd $(DEBUG_PATH); make clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
