##############
# For OSX only
##############
# ARGS=--pthread mstackrealign -O3
# ARGS=-pthread -D_TIMING -mstackrealign -O3
# ARGS=-pthread -mstackrealign -g -D_DEBUG -Wunused

##############
# For Linux
##############
ARGS=-g -D_DEBUG -Wunused -pthread
# ARGS=-O3 -pthread

CC=g++
SRC= memory.o interpreter.o loader.o vm.o 
OBJ_LIBS= jit_intel_lp32.a
JIT_PATH= jit/ia32
EXE= obr

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m32 -pthread -o $(EXE) $(SRC) $(OBJ_LIBS)

jit_intel_lp32.a:
	cd $(JIT_PATH); make	
	
%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	cd $(JIT_PATH); make clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
