# ARGS=-g -D_DEBUGGER -Wall -pthread
# ARGS=-g -D_DEBUG -D_DEBUGGER -Wall -pthread
ARGS=-O3 -D_DEBUGGER -Wall -pthread

CC=g++
SRC=tree.o scanner.o parser.o debugger.o
OBJ_LIBS=compiler.a ../jit_intel_lp32.a ../memory.a
COMPILER_PATH=..
MEM_PATH=../os/posix
JIT_PATH=../jit/ia32
EXE=obd

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m32 -o $(EXE) $(SRC) $(OBJ_LIBS) -ldl -pthread -lssl -lcrypto

compiler.a:
	cd $(COMPILER_PATH); make	

../memory.a:
	cd $(MEM_PATH); make

../jit_intel_lp32.a:
	cd $(JIT_PATH); make
	
%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	cd $(COMPILER_PATH); make clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
