##############
# For OSX only
##############
# ARGS=-pthread -mstackrealign -O3
# ARGS=-pthread -D_TIMING -mstackrealign -O3
# ARGS=-pthread -mstackrealign -g -D_DEBUG -Wunused
# ARGS=-g -mstackrealign -Wunused -D_DEBUG -pthread -D_DEBUGGER

##############
# For Linux
##############
# ARGS=-g -Wunused -pthread
ARGS=-g -D_DEBUG -D_DEBUGGER -Wunused -pthread
# ARGS=-g -D_DEBUG -Wunused -pthread
# ARGS=-g -Wunused -D_JIT_SERIAL -pthread
# ARGS=-O3 -pthread

CC=g++
SRC=tree.o scanner.o parser.o debugger.o
OBJ_LIBS=compiler.a ../jit_intel_lp32.a ../memory.a
COMPILER_PATH=..
EXE=obd

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m32 -pthread -o $(EXE) $(SRC) $(OBJ_LIBS)

compiler.a:
	cd $(COMPILER_PATH); make	
	
%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	cd $(COMPILER_PATH); make clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
