-- mod-version:3
local syntax = require "core.syntax"

syntax.add {
  name = "Objeck",
  files = "%.obs$",
  comment = "#",
  patterns = {
    { pattern = { "#~", "~#" },             type = "comment"  },
    { pattern = "#.*",                      type = "comment"  },
    { pattern = { '"', '"', '\\' },         type = "string"   },
    { pattern = "'\\u%x%x%x%x'",            type = "string"   }, -- character unicode escape sequence
    { pattern = "'\\?.'",                   type = "string"   }, -- character literal
    { pattern = "-?0x%x+",                  type = "number"   },
    { pattern = "-?0b[0-1]+",               type = "number"   },
    { pattern = "-?%d+[%d%.eE]*f?",         type = "number"   },
    { pattern = "-?%.?%d+f?",               type = "number"   },
    { pattern = "[%+%-=/%*%^%%<>!~|&]",     type = "operator" },
    { pattern = ":=",                       type = "operator" },
    { pattern = "[%a_][%w_]*%f[(]",         type = "function" },
    { pattern = "@[%a_][%w_]*",             type = "function" },
    { pattern = "[%a_][%w_]*",              type = "symbol"   },
  },
  symbols = {
    -- keywords and contextual keywords
    ["class"] = "keyword",
    ["method"] = "keyword",
    ["function"] = "keyword",
    ["public"] = "keyword",
    ["abstract"] = "keyword",
    ["private"] = "keyword",
    ["static"] = "keyword",
    ["native"] = "keyword",
    ["virtual"] = "keyword",
    ["Parent"] = "keyword",
    ["As"] = "keyword",
    ["from"] = "keyword",
    ["implements"] = "keyword",
    ["interface"] = "keyword",
    ["enum"] = "keyword",
    ["alias"] = "keyword",
    ["consts"] = "keyword",
    ["bundle"] = "keyword",
    ["use"] = "keyword",
    ["leaving"] = "keyword",
    ["if"] = "keyword",
    ["else"] = "keyword",
    ["do"] = "keyword",
    ["while"] = "keyword",
    ["select"] = "keyword",
    ["break"] = "keyword",
    ["continue"] = "keyword",
    ["other"] = "keyword",
    ["for"] = "keyword",
    ["each"] = "keyword",
    ["reverse"] = "keyword",
    ["label"] = "keyword",
    ["return"] = "keyword",
    ["critical"] = "keyword",
    ["New"] = "keyword",
    ["and"] = "keyword",
    ["or"] = "keyword",
    ["xor"] = "keyword",
    -- types
    ["Nil"] = "keyword2",
    ["Byte"] = "keyword2",
    ["ByteRef"] = "keyword2",
    ["Int"] = "keyword2",
    ["IntRef"] = "keyword2",
    ["Float"] = "keyword2",
    ["FloatRef"] = "keyword2",
    ["Char"] = "keyword2",
    ["CharRef"] = "keyword2",
    ["Bool"] = "keyword2",
    ["BoolRef"] = "keyword2",
    ["String"] = "keyword2",
    ["BaseArrayRef"] = "keyword2",
    ["BoolArrayRef"] = "keyword2",
    ["ByteArrayRef"] = "keyword2",
    ["CharArrayRef"] = "keyword2",
    ["FloatArrayRef"] = "keyword2",
    ["IntArrayRef"] = "keyword2",
    ["StringArrayRef"] = "keyword2",
    ["Func2Ref"] = "keyword2",
    ["Func3Ref"] = "keyword2",
    ["Func4Ref"] = "keyword2",
    ["FuncRef"] = "keyword2",
    -- literals
    ["true"]       = "literal",
    ["false"]      = "literal",
    --["Nil"]        = "literal",
  },
}

