# ARGS=-g -D_DEBUGGER  -D_OBJECK_NATIVE_LIB_PATH  -Wall -pthread
# ARGS=-g -D_DEBUG -D_DEBUGGER  -D_OBJECK_NATIVE_LIB_PATH  -Wall -pthread
ARGS=-O3 -Wall -Wno-unused-function -std=c++11 -Wno-strict-overflow -Wall -D_OBJECK_NATIVE_LIB_PATH -D_DEBUGGER -Wall -pthread

CC=g++
SRC=tree.o scanner.o parser.o debugger.o
OBJ_LIBS=../vm/compiler.a ../vm/jit_intel_lp32.a ../vm/memory.a
VM_PATH=../vm
MEM_PATH=../vm/arch
JIT_PATH=../vm/arch/jit/ia32
EXE=obd

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m32 -o $(EXE) $(SRC) $(OBJ_LIBS) -Wno-unused-function -ldl -pthread -lreadline -lssl -lcrypto -lz -static-libstdc++ -static-libgcc

../vm/compiler.a:
	cd $(VM_PATH); make -f make/Makefile.obd32

../vm/memory.a:
	cd $(MEM_PATH); make -f Makefile.32

../vm/jit_intel_lp32.a:
	cd $(JIT_PATH); make -f Makefile.32
	
%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	cd $(VM_PATH); make -f make/Makefile.obd32 clean
	rm -f $(EXE) *.o *~
