# ARGS=-g -D_DEBUG  -Wunused -Wall -Wno-unused-function
ARGS=-O3 -Wall -Wno-unused-function -std=c++11

CC=g++
AR=ar
SRC=logger.o
LIB=../compiler/logger.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
