# ARGS=-g -Wall -D_X64 -D_DEBUG -Wno-unused-function
# ARGS=-g -Wall -D_X64 -D_DEBUG -D_GC_SERIAL -Wno-unused-function
ARGS=-O3 -Wall -D_X64 -Wno-unused-function -std=c++11

CC=g++
AR=ar
SRC=memory.o
LIB=../memory.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
