ARGS=-O3 -Wall -D_ARM64- D_RPI4 -Wno-unused-function -std=c++17

AR=ar
SRC=memory.o
LIB=../memory.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CXX) $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
