ARGS=-O3 -flto=auto -Wall -D_X64 -Wno-unused-function -std=c++20 -mavx2 -fno-sanitize-recover

AR=gcc-ar
SRC=memory.o
LIB=../memory.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CXX) -m64 $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
