ARGS=-O3 -Wall -D_ARM64 -Wno-unused-function -std=c++17

CC=g++
AR=ar
SRC=memory.o
LIB=../memory.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
