ARGS=-g -D_DEBUG -D_ARM32 -Wunused -Wall -Wno-unused-function -std=c++11 -std=c++11
# ARGS=-O3 -D_ARM64 -D_RPI64 -Wall -Wno-unused-function -std=c++11 -std=c++11

CC=g++
AR=ar
SRC= memory.o
LIB= ../memory.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
