# ARGS=-g -Wall -pthread -D_X64 -D_JIT_SERIAL -D_DEBUG -Wno-unused-function -std=c++11
# ARGS=-g -Wall -pthread -D_X64 -D_JIT_SERIAL -D_DTIMING -Wno-unused-function
ARGS=-O3 -Wall -pthread -D_X64 -D_OBJECK_NATIVE_LIB_PATH -Wno-unused-function -std=c++11

CC=g++
SRC=common.o interpreter.o loader.o vm.o posix_main.o 
OBJ_LIBS= jit_amd_lp64.a memory.a
MEM_PATH= arch
JIT_PATH= arch/jit/amd64
EXE= obr

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m64 -o $(EXE) $(SRC) $(OBJ_LIBS) -lssl -lcrypto -ldl -lz -pthread

memory.a:
	cd $(MEM_PATH); make -f make/Makefile.64
	
jit_amd_lp64.a:
	cd $(JIT_PATH); make -f make/Makefile.64
	
%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	cd $(MEM_PATH); make clean -f make/Makefile.64
	cd $(JIT_PATH); make clean -f make/Makefile.64
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
