all: clean build 

build:
	cd compiler; make -j2 OBJECK_LIB_PATH=\\\"/usr/share/objeck-lang\\\"
	cd vm; make -j2 OBJECK_NATIVE_LIB_PATH=\\\"/usr\\\"
	cd vm/debugger; make -j2 OBJECK_NATIVE_LIB_PATH=\\\"/usr\\\"
	cd utilities; make -j2
	cd lib/odbc; make -j2
	cd lib/openssl; make -j2

install:
	mkdir -p ${BINDIR}
	cp compiler/obc ${BINDIR}
	cp utilities/obu ${BINDIR}
	cp vm/obr ${BINDIR}
	cp vm/debugger/obd ${BINDIR}
	mkdir -p ${MANDIR}
	cp man/*.1 ${MANDIR}
	mkdir -p ${DATADIR}
	cp objk_lib/*.obl ${DATADIR}
	mkdir -p ${LIBDIR}
	mkdir -p ${LIBDIR}/objeck-lang
	cp lib/odbc/*.so ${LIBDIR}/objeck-lang
	cp lib/openssl/*.so ${LIBDIR}/objeck-lang
	mkdir -p ${DOCDIR}
	cp doc/readme.htm ${DOCDIR}
	cp doc/*.tgz ${DOCDIR}
	
clean:
	cd compiler; make clean
	cd vm; make clean
	cd vm/debugger; make clean
	cd utilities; make clean
