ARGS=-O3 -flto=auto -mcpu=native -Wall -Wno-unused-function -std=c++20 -Wno-unused-variable

AR=gcc-ar
SRC=jit_common.o
LIB=arm64/jit_common.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CXX) $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
