ARGS=-O3 -Wall -Wno-unused-function -std=c++11 -Wno-unused-variable

CC=g++
AR=ar
SRC=jit_common.o
LIB=amd64/jit_common.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
