ARGS=-O3 -Wall -std=c++17 -Wno-unused-function -Wno-unused-variable

AR=ar
SRC=jit_common.o
LIB=amd64/jit_common.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CXX) -m64 $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
