CC=/sysgcc/raspberry/bin/arm-linux-gnueabihf-g++
# ARGS=-g -D_SYSTEM -D_DEBUG -Wall -Wno-unused-function
ARGS=-g -D_DEBUG -Wall -Wno-unused-function
# ARGS=-O3 -Wall -Wno-unused-function
SRC=../shared/logger.o types.o tree.o scanner.o parser.o linker.o context.o intermediate.o optimization.o emit.o compiler.o posix_main.o
EXE=obc

$(EXE): $(SRC)
	$(CC) -o $(EXE) $(SRC)

%.o: %.cpp
	$(CC) $(ARGS) -c $< 

clean:
	rm -f $(EXE) *.o *~
