CC=g++
ARGS=-O3 -Wall -Wno-unused-function -D_ARM64 -std=c++17
SRC=../shared/logger.o types.o tree.o scanner.o parser.o linker.o context.o intermediate.o optimization.o emit.o compiler.o posix_main.o
OBJ_LIBS=logger.a
LOGGER_PATH=../shared
EXE=obc

$(EXE): $(OBJ_LIBS) $(SRC)
	$(CC) -o $(EXE) $(SRC) -lz

%.o: %.cpp
	$(CC) $(ARGS) -c $<

logger.a:
	cd $(LOGGER_PATH); make -f make/Makefile.arm64

clean:
	cd $(LOGGER_PATH); make clean -f make/Makefile.arm64
	rm -f $(EXE) *.o *~
