CC=g++
ARGS=-O3 -Wall -Wno-unused-function -D_X64 -std=c++17
SRC=../shared/logger.o types.o tree.o scanner.o parser.o linker.o context.o intermediate.o optimization.o emit.o compiler.o posix_main.o
OBJ_LIBS=logger.a
LOGGER_PATH=../shared
EXE=obc

$(EXE): $(OBJ_LIBS) $(SRC) 
	$(CC) -m64 -o $(EXE) $(SRC) -lz

%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

logger.a:
	cd $(LOGGER_PATH); make -f make/Makefile.amd64

clean:
	cd $(LOGGER_PATH); make -f make/Makefile.amd64 clean
	rm -f $(EXE) *.o *~
