ARGS=-g -D_DEBUG -D_X64 -Wunused
# ARGS=-O2 -D_X64

CC=g++
SRC= memory.o interpreter.o loader.o vm.o 
OBJ_LIBS= jit_amd_lp64.a
JIT_PATH= jit/amd64
EXE= obr

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m64 -pthread -o $(EXE) $(SRC) $(OBJ_LIBS)

jit_amd_lp64.a:
	cd $(JIT_PATH); make	
	
%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	cd $(JIT_PATH); make clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
