ARGS=-O3 -Wall -pthread -Wno-unused-function -D_UTILS

CC=g++
SRC=../compiler/types.o ../compiler/linker.o ../vm/loader.o symbols.o
COMPILER_PATH=..
EXE=obu

$(EXE): $(SRC) 
	$(CC) -m32 -pthread -o $(EXE) $(SRC) $(OBJ_LIBS)

%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
