ARGS=-O3 -Wall -pthread -D_X64 -D_UTILS -Wno-unused-function -std=c++11

CC=g++
SRC=../compiler/types.o ../compiler/linker.o ../vm/loader.o symbols.o
COMPILER_PATH=..
EXE=obu

$(EXE): $(SRC) 
	$(CC) -m64 -pthread -o $(EXE) $(SRC) $(OBJ_LIBS)

%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
