ARGS=-g -D_DEBUG -D_ARM32 -Wunused -Wall -Wno-unused-function -std=c++11 -std=c++11
# ARGS=-O3 -Wall -D_ARM32 -Wno-unused-function -Wno-unused-function

CC=arm-linux-gnueabihf-g++
AR=arm-linux-gnueabihf-ar
SRC= jit_arm_a32.o
LIB= ../../jit_arm_a32.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
