###############
# For OSX only
###############
# ARGS=-mstackrealign -O2
# ARGS=-D_TIMING -mstackrealign -O2
# ARGS=-mstackrealign -g -D_DEBUG -Wunused

###############
# For Linux
###############
# ARGS=-g -D_DEBUG  -Wunused
# ARGS=-g -Wunused
ARGS=-O2

CC=g++
AR=ar
SRC= jit_intel_lp32.o
LIB= ../../jit_intel_lp32.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
