# ARGS=-g -D_DEBUG  -Wunused -Wall -Wno-unused-function
ARGS=-O3 -Wall -Wno-unused-function -Wno-unused-function

CC=g++
AR=ar
SRC= jit_intel_lp32.o
LIB= ../../jit_intel_lp32.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
