ARGS=-O3 -Wall -Wno-unused-function

CC=g++
AR=ar
SRC=jit_intel_lp32.o
LIB=../../jit_intel_lp32.a

$(LIB): $(SRC)
	$(AR) -cvq -s $(LIB) $(SRC)

%.o: %.cpp
	$(CC) -m32 -I"../../lib/openssl/win32/include" -D_MINGW -static -static-libstdc++ $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
