ARGS=-O3 -Wall -Wno-unused-function -std=c++17

CC=g++
AR=ar
SRC=win32.o
LIB=../../win32.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) -m64 -I/usr/include $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
