ARGS=-O3 -Wall -Wno-unused-function -std=c++17

AR=ar
SRC=win32.o
LIB=../../win32.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CXX) -m64 $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
