# ARGS=-g -D_DEBUG -D_ARM64 -Wunused -Wall -Wno-unused-function -std=c++11 -std=c++11
ARGS=-O3 -D_ARM64 -D_RPI64 -Wall -Wno-unused-function -std=c++11 -std=c++11 -Wno-unused-function

CC=g++
AR=ar
SRC=jit_arm_a64.o
LIB= ../../../jit_arm_a64.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) $(ARGS) -c $< -I../../../../lib/openssl/macos/include

clean:
	rm -f *.o *~ $(LIB)
