CC=g++
# ARGS=-g -D_SYSTEM -D_DEBUG -Wunused
# ARGS=-g -D_DEBUG -Wunused
ARGS=-O3 -Wunused
SRC=types.o tree.o scanner.o parser.o linker.o context.o intermediate.o optimize.o target.o compiler.o
EXE=obc

$(EXE): $(SRC)
	$(CC) -m64 -o $(EXE) $(SRC)

%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	rm -f $(EXE) *.o *~
