ARGS=-O3 -Wall -Wno-unused-function -std=c++17

AR=ar
SRC=logger.o
LIB=../compiler/logger.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CXX) $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
