ARGS=-O3 -flto=auto -mcpu=native -Wall -Wno-unused-function -std=c++20

AR=gcc-ar
SRC=logger.o sys.o
LIB=../compiler/sys.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CXX) $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
