ARGS=-g -D_DEBUG  -Wunused -Wall -Wno-unused-function -std=c++11
# ARGS=-O3 -Wall -Wno-unused-function -std=c++11 -std=c++11

CC=arm-linux-gnueabihf-g++
AR=arm-linux-gnueabihf-ar
SRC= memory.o
LIB= ../../memory.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
