# ARGS=-O3 -Wall -Wno-unused-function -D_X64 -std=c++17
ARGS=-g -Wall -Wno-unused-function -D_X64 -D_DIAG_LIB -std=c++17
SRC=../../compiler/scanner.o ../../compiler/parser.o ../../compiler/context.o ../../compiler/tree.o ../../compiler/types.o diags.o 
EXE=diags

$(EXE): $(OBJ_LIBS) $(SRC) 
	$(CXX) -m64 -o $(EXE) $(SRC) -lz

%.o: %.cpp
	$(CXX) -m64 $(ARGS) -c $< 

clean:
	rm -f $(EXE) *.o *~

