all: clean build 

build:
	cd compiler; make
	cd vm; make
	cd vm/debugger; make
	cd utilities; make

install:
	mkdir -p ${BINDIR}
	cp compiler/obc ${BINDIR}
	cp utilities/obu ${BINDIR}
	cp vm/obr ${BINDIR}
	cp vm/debugger/obd ${BINDIR}
	mkdir -p ${MANDIR}
	cp man/*.1 ${MANDIR}

clean:
	cd compiler; make clean
	cd vm; make clean
	cd vm/debugger; make clean
	cd utilities; make clean
