all: clean build install

build:
	cd compiler; make
	cd vm; make
	cd vm/debugger; make
	cd utilities; make

install:
#	mkdir -p ../bin
	cd utilities; cp obu $DESTDIR
	cd compiler; cp obc $DESTDIR
	cd vm; cp obr $DESTDIR
	cd vm/debugger; cp obd $DESTDIR

clean:
	cd compiler; make clean
	cd vm; make clean
	cd vm/debugger; make clean
	cd utilities; make clean
