all: clean build 

build:
	cd compiler; make
	cd vm; make
	cd vm/debugger; make
	cd utilities; make

install:
	mkdir -p ${DESTDIR}
	cp compiler/obc ${DESTDIR}
	cp utilities/obu ${DESTDIR}
	cp vm/obr ${DESTDIR}
	cp vm/debugger/obd ${DESTDIR}

clean:
	cd compiler; make clean
	cd vm; make clean
	cd vm/debugger; make clean
	cd utilities; make clean
