/* 
**  mod_hello.c -- Apache sample hello module
**  [Autogenerated via ``apxs -n hello -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_hello.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /hello in as follows:
**
**    #   apache2.conf
**    LoadModule hello_module modules/mod_hello.so
**    <Location /hello>
**    SetHandler hello
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /hello and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/hello 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_hello.c
*/ 

#include <dlfcn.h>

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "http_log.h"

typedef void (*vm_init_def)(const char*, const char*, const char*);
typedef void (*vm_call_def)(request_rec*);
typedef void (*vm_exit_def)();

static vm_call_def call_ptr;

/* The sample content handler */
static int hello_init(request_rec *r, apr_pool_t *p)
{
  ap_log_error(APLOG_MARK, APLOG_ERR, 0, r->server, "*** Init - start ***");

  void* dynamic_lib = dlopen("/tmp/obr.so", RTLD_LAZY);
  if(!dynamic_lib) {
    ap_log_error(APLOG_MARK, APLOG_ERR, 0, r->server, ">>> Runtime error loading DLL: %s\n", 
		 dlerror());
    exit(1);
  }

  // call load function
  char* error;
  vm_init_def init_ptr = (vm_init_def)dlsym(dynamic_lib, "Init");
  if((error = dlerror()) != NULL)  {
    ap_log_error(APLOG_MARK, APLOG_ERR, 0, r->server, ">>> Runtime error calling function: %s\n",
		 error);
    exit(1);
  }

  call_ptr = (vm_call_def)dlsym(dynamic_lib, "Call");
  if((error = dlerror()) != NULL)  {
    ap_log_error(APLOG_MARK, APLOG_ERR, 0, r->server, ">>> Runtime error calling function: %s\n", 
		 error);
    exit(1);
  }

  // call function
  (*init_ptr)("/tmp/a.obe", "ApacheModule", "ApacheModule:Request:o.Apache.Request,");
  
  ap_log_error(APLOG_MARK, APLOG_ERR, 0, r->server, "*** Init - end ***");
}

/* The sample content handler */
static int hello_handler(request_rec *r)
{
  if (strcmp(r->handler, "hello")) {
    return DECLINED;
  }
  
  r->content_type = "text/html";      
  if (!r->header_only) {
    (*call_ptr)(r);
    ap_rputs("Done.", r);
  }
  
  return OK;
}

static void hello_register_hooks(apr_pool_t *p)
{
  ap_hook_post_config(hello_init, NULL, NULL, APR_HOOK_MIDDLE);
  ap_hook_handler(hello_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA hello_module = {
  STANDARD20_MODULE_STUFF, 
  NULL,                  /* create per-dir    config structures */
  NULL,                  /* merge  per-dir    config structures */
  NULL,                  /* create per-server config structures */
  NULL,                  /* merge  per-server config structures */
  NULL,                  /* table of config file commands       */
  hello_register_hooks  /* register hooks                      */
};

