# ARGS=-g -Wall -pthread -D_X64 -D_DEBUG -D_DEBUGGER
# ARGS=-g -Wall -pthread -D_X64 -D_DEBUGGER
ARGS=-O3 -Wall -Wall -Wno-unused-function -std=c++11 -Wno-strict-overflow -pthread -D_X64 -D_DEBUGGER

CC=g++
SRC=tree.o scanner.o parser.o debugger.o
OBJ_LIBS=compiler.a ../jit_amd_lp64.a ../memory.a
COMPILER_PATH=..
MEM_PATH=../os/posix
JIT_PATH=../jit/amd64
EXE=obd

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m64 -pthread -o $(EXE) $(SRC) $(OBJ_LIBS) -Wunused-function -ldl -lcrypto -lssl

compiler.a:
	cd $(COMPILER_PATH); make	-f Makefile.obd64

../memory.a:
	cd $(MEM_PATH); make

../jit_amd_lp64.a:
	cd $(JIT_PATH); make
	
%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	cd $(COMPILER_PATH); make -f Makefile.obd64 clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~
