###############
# MinGW
###############
# ARGS=-g -D_DEBUG  -Wall -g
ARGS=-D_MINGW -O3 -Wall

CC=g++
AR=ar
SRC=memory.o
LIB=../../memory.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) -m32 -D_MINGW -static -static-libstdc++ $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
