ARGS=-g -D_DEBUG  -Wunused -Wall -Wno-unused-function -std=c++11 -std=c++11
# ARGS=-O3 -Wall -Wno-unused-function -std=c++11 -std=c++11 -Wno-unused-function

CC=g++
AR=ar
SRC= jit_arm_a32.o
LIB= ../../jit_arm_a32.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
