CC=g++
# ARGS=-g -D_DEBUG -Wall -Wno-unused-function
ARGS=-O3 -Wall -Wno-unused-function -std=c++11
# ARGS=-g -Wall -Wno-unused-function -D_X64 -std=c++11
SRC=launcher.o
EXE=obn

$(EXE): $(OBJ_LIBS) $(SRC) 
	$(CC) -m64 -o $(EXE) $(SRC) -lz

%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 


clean:
	rm -f $(EXE) *.o *~
