.\" Manpage for obc.
.\" Contact objeck@gmail.com to correct errors or typos.
.TH man 1 "13 Dec 2014" "3.3.5.1" "obc man page"
.SH NAME
obc \- compiles Objeck source files
.SH SYNOPSIS
.B obc
[\fB\-src\fR \fIsourcefiles\fR]
[options]
[\fB\-dest\fR \fIoutputfile\fR]
.SH DESCRIPTION
nuseradd is high level shell program for adding users to LDAP server.  On Debian, administrators should usually use nuseradd.debian(8) instead.
.SH OPTIONS
The nuseradd does not take any options. However, you can supply username.
.SH SEE ALSO
obr(1), obd(1), obu(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Randy Hollines (objeck@gmail.com)
