.\" Man page for obu.
.\" Contact object@gmail.com to correct errors or typos.
.TH man 1 "7 Jan 2015" "6.5-2-1" "obd man page"
.SH NAME
obu \- Objeck runtime debugger
.SH SYNOPSIS
.B obu
[\fIlibrary\fR]
.SH DESCRIPTION
obd is a interactive debugger for the Objeck language.
.SH OPTIONS
.IP -exe 
Executable file
.IP -src 
Source directory path
.SH SEE ALSO
obc(1), obr(1), obu(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Randy Hollines (objeck@gmail.com)
