.\" Man page for obu.
.\" Contact object@gmail.com to correct errors or typos.
.TH man 1 "7 Jan 2015" "5.3-3-1" "obu man page"
.SH NAME
obu \- Inspects Objeck libraries
.SH SYNOPSIS
.B obu
[\fIlibrary\fR]
.SH DESCRIPTION
obu is a library inspection tool for the Objeck language.
.SH SEE ALSO
obc(1), obr(1), obd(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Randy Hollines (objeck@gmail.com)
