# ARGS=-g -D_DEBUG  -Wunused
# ARGS=-g -Wunused
ARGS=-O3

CC=g++
AR=ar
SRC= jit_intel_lp64.o
LIB= ../../jit_intel_lp64.a

$(LIB): $(SRC)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) -m64 $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
